apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudwatchlogs-collector
  name: cloudwatchlogs-collector
  namespace: logcollect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudwatchlogs-collector
  template:
    metadata:
      labels:
        app: cloudwatchlogs-collector
    spec:
      serviceAccountName: cloudwatchlogs-collector-sa
      containers:
        - name: cloudwatchlogs-collector
          image: dfdsdk/cloudwatchlogs-collector:eks-0.5
          args:
            - -AwsRegion
            - eu-west-1
            - -LogGroupName
            - $(LOG_GROUP)
            - -LogStreamNamePrefix
            - kube-apiserver-audit-
            - -QueryIntervalHours
            - "12"
            - -S3BucketName
            - $(BUCKET_NAME)
            - -S3Path
            - aws/eks
