resources:
  - serviceaccount.yaml
  - deployment.yaml

vars:
  - name: ROLE_ARN
    objref:
      kind: ConfigMap
      name: environment
      apiVersion: v1
    fieldref:
      fieldpath: data.ROLE_ARN
  - name: LOG_GROUP
    objref:
      kind: ConfigMap
      name: environment
      apiVersion: v1
    fieldref:
      fieldpath: data.LOG_GROUP
  - name: BUCKET_NAME
    objref:
      kind: ConfigMap
      name: environment
      apiVersion: v1
    fieldref:
      fieldpath: data.BUCKET_NAME

configMapGenerator:
  - name: environment
    envs: [vars.env]

configurations:
  - env-var-transformer.yaml
