apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudwatchlogs-collector-sa
  namespace: logcollect
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::999999999999:role/CloudWatchLogsCollector
    eks.amazonaws.com/sts-regional-endpoints: "true"
