apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudwatchlogs-collector-sa
  namespace: logcollect
  annotations:
    eks.amazonaws.com/role-arn: $(ROLE_ARN)
    eks.amazonaws.com/sts-regional-endpoints: "true"
